add_newline = true

format = """$directory$line_break$character"""
right_format = """$cmd_duration$git_branch$python"""

[character]
success_symbol = "[:::](green)"
error_symbol = "[  ](red)"
vimcmd_symbol = "[  ](green)"

[directory]
truncate_to_repo = false
format = " [$path]($style)[$read_only]($read_only_style) "
style='bold purple'
home_symbol=''

[git_branch]
symbol = ""
format = " [on]() [$symbol $branch(:$remote_branch)](bold green)"

[python]
format=' [with]() [${symbol} ${version} ${virtualenv}](bold blue)'
symbol=""

[localip]
ssh_only = false
format = " [$localipv4](blue) "
disabled = false

[cmd_duration]
min_time = 0
format = "[took]() [$duration](bold purple)"
show_milliseconds = true
disabled = false
