add_newline = true
command_timeout = 2000

format = """$hostname$directory$line_break$character"""
right_format = """$cmd_duration$git_branch$python$nix_shell"""

[character]
# success_symbol = "[ \\$](green)"
success_symbol = "[ >∶](green)"
error_symbol = "[ 󰙦 ](red)"
vimcmd_symbol = "[  ](green)"

[directory]
truncate_to_repo = false
format = "in [$path]($style)[$read_only]($read_only_style) "
style='bold purple'

[git_branch]
symbol = ""
format = " [on]() [$symbol $branch(:$remote_branch)](bold green)"

[hostname]
ssh_only = false
format = " on [$hostname](fg:green) "

[python]
format=' [with]() [${symbol} ${version} ${virtualenv}](bold blue)'
symbol=""

[localip]
ssh_only = false
format = " [$localipv4](blue) "
disabled = false

[cmd_duration]
min_time = 0
format = "[took]() [$duration](bold purple)"
show_milliseconds = true
disabled = false

[nix_shell]
disabled = false
impure_msg = ''
pure_msg = 'pure '
format = ' on [ $state$name](bold cyan)'
