add_newline = true
command_timeout = 2000

format = """$shell$hostname$directory$line_break$character"""
right_format = """$cmd_duration$git_branch$python$nix_shell"""

[shell]
fish_indicator = "[  ](bold purple)"
zsh_indicator = " 󰬇"
bash_indicator = " $"
disabled = false

[localip]
ssh_only = false
format = " [$localipv4](blue) "
disabled = false

[character]
# success_symbol = "[ \\$](green)"
success_symbol = "[ >∶](green)"
error_symbol = "[ 󰙦 ](red)"
vimcmd_symbol = "[  ](green)"

[hostname]
ssh_only = false
format = "on [$hostname](fg:green) "

[directory]
truncate_to_repo = false
format = "in [$path]($style)[$read_only]($read_only_style) "
style='bold purple'

[cmd_duration]
min_time = 0
format = "[took]() [$duration](bold purple) "
show_milliseconds = true
disabled = false

[git_branch]
symbol = ""
format = "[on]() [$symbol $branch(:$remote_branch)](bold green) "

[python]
format='[with]() [${symbol} ${version}](bold blue) '
symbol=""

[nix_shell]
disabled = false
impure_msg = ''
pure_msg = 'pure '
format = ' on [ $state$name](bold cyan)'
