[settings]
experimental = true
always_keep_download = false
always_keep_install = false
legacy_version_file = true

[tools]
go = "1.24"
node = "22"
ruby = "3.3"
lua = "latest"
zig = "latest"
rust = "latest"

# Go tools
"go:github.com/air-verse/air" = "latest"
"go:github.com/kisielk/errcheck" = "latest"
"go:golang.org/x/tools/cmd/godoc" = "latest"
"go:github.com/jackyzha0/hugo-obsidian" = "latest"
"go:github.com/a-h/templ/cmd/templ" = "latest"
"go:github.com/traefik/yaegi/cmd/yaegi" = "latest"
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"

# Cargo tools
"cargo:prosemd-lsp" = "latest"
