#!/bin/bash
bash <(curl -sL install-node.now.sh/lts) --yes
sudo add-apt-repository -y ppa:jonathonf/vim
sudo apt -y install vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
cd ~/.vim/bundle/coc.nvim; npm install
