require("adam.options")

require("adam.plugins")
require("adam.color")

require("adam.alpha")
require("adam.augroup")
require("adam.cmp")
require("adam.gitsigns")
require("adam.keys")
require("adam.lsp")
require("adam.lualine")
require("adam.null-ls")
require("adam.pairs")
require("adam.telescope")
-- was quoted out
require("adam.treesitter")
require("adam.whichkey")
require("adam.barbar")
require("adam.copilot")
-- require("adam.iron")
