vim.lsp.set_log_level("debug")
require("adam.options")
require("adam.plugins")
require("adam.color")
require("adam.alpha")
require("adam.augroup")
require("adam.cmp")
require("adam.gitsigns")
require("adam.keys")
require("adam.lsp")
require("adam.format")
require("adam.lint")
require("adam.lualine")
require("adam.luasnip")
require("adam.pairs")
require("adam.telescope")
require("adam.treesitter")
require("adam.whichkey")
require("adam.barbar")

local key = os.getenv("OPEN_AI_KEY")
if key then
	require("adam.copilot")
end
require("adam.signature")
