#!/usr/bin/env sh
#
#  auto balance = all windows always occupy the same space
#  split ratio = if auto balance disabled, determines how much space a new window occupies
#  0.5 = both occupy half

yabai -m space 3 --label slack
yabai -m rule --add app="^Slack$" space=slack
yabai -m rule --add app="^Swinsian$" space=slack

yabai -m config --space 1                    \
    layout                       bsp         \
    auto_balance                 off         \
    split_ratio                  0.5        \
    split_type                   vertical    \
    mouse_follows_focus          off         \
    focus_follows_mouse          off         \
    mouse_action1                off           \
    mouse_action2                off         \
    mouse_drop_action            off

yabai -m config --space 2                    \
    layout                       bsp         \
    auto_balance                 off         \
    split_ratio                  0.5        \
    split_type                   vertical    \
    mouse_follows_focus          off         \
    focus_follows_mouse          off         \
    mouse_action1                off           \
    mouse_action2                off         \
    mouse_drop_action            off

# float some windows always
yabai -m rule --add app='^System Settings$' manage=off
yabai -m rule --add app='^Finder$' manage=off
yabai -m rule --add app='^Excel$' manage=off
yabai -m rule --add app='^Slack$' manage=off
yabai -m rule --add app='^Swinsian$' manage=off
yabai -m rule --add app='^ColorSlurp$' manage=off
yabai -m rule --add app='^Preview$' manage=off
