#!/usr/bin/env sh
#
#  auto balance = all windows always occupy the same space
#  split ratio = if auto balance disabled, determines how much space a new window occupies
#  0.5 = both occupy half

yabai -m space 2 --label slack
yabai -m rule --add app="^Slack$" space=slack
yabai -m rule --add app="^Swinsian$" space=slack

yabai -m config --space 1                      \
    layout                       bsp           \
    auto_balance                 on            \
    split_ratio                  0.25          \
    split_type                   horizontal    \

# float some windows always
yabai -m rule --add app='^System Settings$' manage=off

echo "yabai configuration loaded.."
