#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

#  auto balance = all windows always occupy the same space
#  split ratio = if auto balance disabled, determines how much space a new window occupies
#  0.5 = both occupy half

yabai -m config --space 1                       \
    layout                       bsp            \
    auto_balance                 off            \
    # split_ratio                  0.50           \
    # split_type                   auto           \
    # window_origin_display        default        \
    # window_placement             second_child   \
    # window_zoom_persist          on             \
    # window_topmost               off            \
    # window_shadow                on             \
    # window_animation_duration    0.0            \
    # window_animation_frame_rate  120            \
    # window_opacity_duration      0.0            \
    # active_window_opacity        1.0            \
    # normal_window_opacity        0.90           \
    # window_opacity               off            \
    # insert_feedback_color        0xffd75f5f     \
    # active_window_border_color   0xff775759     \
    # normal_window_border_color   0xff555555     \
    # window_border_blur           off            \
    # window_border_hidpi          off             \
    # window_border                off            \
    # mouse_modifier               fn             \
    # mouse_action1                move           \
    # mouse_action2                resize         \
    # mouse_drop_action            swap

echo "yabai configuration loaded.."
