#!/usr/bin/env zsh

prefix=$HOME/personal/todo

# -m = multi-select
files=$(find $prefix -type f | fzf -m)

# protects fzf interrupted by Ctrl-C
if [ $? -eq 0 ]; then
  prefixed_files=()
  for file in ${(f)files}; do
    prefixed_files+="${file}"
  done
  $EDITOR ${prefixed_files[@]}
fi
