#!/usr/bin/env zsh

TERM_HEIGHT=$(tput lines)
MIN_HEIGHT=20

# prompt for files using fzf
files=$(if [ "$TERM_HEIGHT" -ge "$MIN_HEIGHT" ]; then
    fzf --preview 'bat -p --color=always {}' --height 60% -m
else
    fzf --no-preview --height 40% -m
fi)

# check if fzf was interrupted by Ctrl-C
if [ $? -eq 0 ]; then
  $EDITOR ${(f)files}
fi
