name: test

on:
  push:


jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make nix-setup OS=linux devShell=''
      - run: . ./nix/load-linux.sh && make test OS=linux
      - run: . ./nix/load-linux.sh && sudo make setup-linux -o nix-setup OS=linux
      - run: . ./nix/load-linux.sh && sudo make js python OS=linux

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: make nix-setup OS=macos
      - run: . ./nix/load-macos.sh && make test -o nix-setup OS=macos
