---
name: test
on:
  push:
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      XDG_CONFIG_HOME: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3
      - run: rm ~/.bashrc ~/.bash_profile
      - run: make setup-ubuntu
  macos:
    runs-on: macos-latest
    env:
      XDG_CONFIG_HOME: ${{ github.workspace }}
      NIXPKGS_ALLOW_BROKEN: 1
    steps:
      - uses: actions/checkout@v3
      - run: rm ~/.bashrc ~/.bash_profile
      - run: make setup-macos
