name: test

on:
  push:


jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make nix-install-ubuntu
      - run: . ./nix/load-ubuntu.sh && just test

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: make nix-install-macos
      - run: . ./nix/load-macos.sh && just test
