name: test

on:
  push:


jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make nix-setup OS=linux devShell=''
      - run: . ./nix/load-linux.sh && make test OS=linux

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: make nix-setup OS=macos devShell=''
      - run: . ./nix/load-macos.sh && make test -o nix-setup OS=macos

  dev-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: make nix-setup OS=macos
      - run: . ./nix/load-macos.sh && sudo make setup-macos -o nix-setup OS=macos -o homebrew
      - run: . ./nix/load-macos.sh && sudo make js python OS=macos
