---
name: test
on:
  push:
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      XDG_CONFIG_HOME: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3
      - run: rm ~/.bashrc ~/.bash_profile
      # not brew packages as it's annoying to do the $PATH changes after install....
      - run: make setup-ubuntu -o brew-pkgs
  macos:
    runs-on: macos-latest
    env:
      XDG_CONFIG_HOME: ${{ github.workspace }}
      NIXPKGS_ALLOW_BROKEN: 1
    steps:
      - uses: actions/checkout@v3
      - run: rm ~/.bashrc ~/.bash_profile
      # not brew packages as it's annoying to do the $PATH changes after install....
      - run: make setup-macos -o brew-pkgs
