name: test

on:
  push:


jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make nix-install OS=linux devShell=''
      - run: . ./nix/load-linux.sh && just test

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: make nix-install OS=macos devShell=''
      - run: . ./nix/load-macos.sh && just test
