---
name: test
on:
  push:
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      XDG_CONFIG_HOME: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3
      - run: make nix-pkgs OS=ubuntu devShell=''
      - run: . ./nix/load-ubuntu.sh && make test -o setup-nix OS=ubuntu STOW_ARGS='--v
          --adopt'
      - run: . ./nix/load-ubuntu.sh && sudo -E make setup-ubuntu -o setup-nix OS=ubuntu
          STOW_ARGS='--v --adopt'
      #  TODO having problems with zsh being available
      #  can't set $PATH correctly
      # - run: . ./nix/load-linux.sh && sudo -E make js python OS=linux
  macos:
    runs-on: macos-latest
    env:
      XDG_CONFIG_HOME: ${{ github.workspace }}
      NIXPKGS_ALLOW_BROKEN: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: make nix-pkgs OS=macos
      - run: . ./nix/load-macos.sh && make test -o setup-nix OS=macos STOW_ARGS='--v
          --adopt'
