name: test

on:
  push:


jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: . ./nix/load-linux.sh && make test OS=linux devShell=''

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: . ./nix/load-macos.sh && make test OS=macos devShell=''
